services:
  app:
    image: ghcr.io/lkindo/sr:latest
    container_name: sr-app
    restart: always
    ports:
      - '80:3000'
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sr-net

  db:
    image: postgres:16-alpine
    container_name: sr-db
    restart: always
    environment:
      - POSTGRES_USER=lkind
      - POSTGRES_PASSWORD=sr1234
      - POSTGRES_DB=sr_db
    ports:
      - '5432:5432'
    volumes:
      - sr_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U lkind -d sr_db']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sr-net

volumes:
  sr_db_data:

networks:
  sr-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
