services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sr-app:latest
    container_name: sr-app
    restart: always
    ports:
      - '3001:3000'
    env_file:
      - .env.docker
    environment:
      - NODE_OPTIONS=--max-old-space-size=450
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:16-alpine
    container_name: sr-db
    restart: always
    environment:
      - POSTGRES_USER=lkind
      - POSTGRES_PASSWORD=sr1234
      - POSTGRES_DB=sr_db
    ports:
      - '5432:5432'
    volumes:
      - sr_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U lkind -d sr_db']
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  sr_db_data:
